In [1]:
import os
import yaml

config_path = os.path.join(os.path.dirname(os.getcwd()), "config.yaml")
with open(config_path, "r") as f:
    config_data = yaml.safe_load(f)

In [2]:
catalog = config_data["databricks_config"]["catalog"]
schema = config_data["databricks_config"]["schema"]
spark.sql(f"USE CATALOG {catalog};")
spark.sql(f"USE SCHEMA {schema}")

DataFrame[]

In [3]:
spark.sql(
    """
    CREATE OR REPLACE FUNCTION row_filter_by_client(row_client_id STRING)
    RETURNS BOOLEAN
    LANGUAGE SQL
    DETERMINISTIC
    COMMENT 'Row filter: returns TRUE if row belongs to current user, or if user is mapped to client_id "all"'
    RETURN (
        row_client_id = (
            SELECT client_id 
            FROM identity_mappings
            WHERE username = current_user()
            LIMIT 1
        )
        OR (
            SELECT client_id 
            FROM identity_mappings
            WHERE username = current_user()
            LIMIT 1
        ) = 'all'
    );
    """
)

DataFrame[]

In [4]:
spark.sql(
    """
    ALTER TABLE customer_transactions
    SET ROW FILTER row_filter_by_client ON (client_id);
    """
)

DataFrame[]

In [5]:
display(spark.sql("""
          DESCRIBE TABLE EXTENDED customer_transactions;
          """))

DataFrame[col_name: string, data_type: string, comment: string]

In [7]:
display(spark.sql("SELECT * FROM customer_transactions"))

DataFrame[client_id: string, product_name: string, revenue: double]